### ISSUE TITLE
Editor Play button not working

### ISSUE THREAD

**Issue by NatRobson** [daaain/JSSoundRecorder#18]
The editor play button is not working, any ideas?. Apart from that everything else is great! Please update this amazing code

**Comment by daaain** [comment]
Hey @NatRobson, have you found out what the issue was?

I'm not maintaining this code base and a lot of Audio APIs used are experimental and often prefixed, but if you figure it out and open a PR I can review it!

**Comment by NatRobson** [comment]
Hey @daaain, basically i edited your code to where it was the editor only and when i drag and drop an audio file the editor play button dosnt work. The editor play button only plays when loaded via the sounds edit button... 
`editButton.onclick = function(e) {
    $('.recorder.container').addClass('hide');
    $('.editor.container').removeClass('invisible');

    currentEditedSoundIndex = $(e.target).closest('tr').index();
    
    var f = new FileReader();
    f.onload = function(e) {
        audio_context.decodeAudioData(e.target.result, function(buffer) {
          console.warn(buffer);
          $('#audioLayerControl')[0].handleAudio(buffer);
        }, function(e) {
          console.warn(e);
        });
    };
    f.readAsArrayBuffer(blob);
  };`

 Something in the code above is allowing the editor to play, im currently trying to figure out what in the code above allows the play button to work properly. Thanks for your reply.
