### ISSUE TITLE
Echoing effect

### ISSUE THREAD

**Issue by aaryadev** [daaain/JSSoundRecorder#2]
Hi code  works great but it has  echoing  effect i tested  with  Chrome 32.02 ,win7(64bit), but in ubuntu 13.10 the  echoing  was very less.

**Comment by daaain** [comment]
I think that might just be a feedback loop and you have different microphone volume settings in each OS? You need to use a headphone or turn the monitoring volume down, there's no filter in the code to get rid of feedback.

**Comment by aaryadev** [comment]
Thanks for quick reply , I will test with different mic and  system .

Thanks again
