### ISSUE TITLE
bug in wavetrack.js

### ISSUE THREAD

**Issue by bobvoorneveld** [daaain/JSSoundRecorder#3]
Hi there,

Is fiddling around with your great library. But saving an edited file doesn't work. I found a small bug in your code at wavetrack.js.

your code from #133 onwards:

var waveByteRate = waveSampleRate \* waveNumChannels \* waveBitsPerSample / 8;
var waveBlockAlign = waveNumChannels \* waveBitsPerSample / 8;
var waveBitsPerSample = 16;

should be:

var waveBitsPerSample = 16;
var waveByteRate = waveSampleRate \* waveNumChannels \* waveBitsPerSample / 8;
var waveBlockAlign = waveNumChannels \* waveBitsPerSample / 8;

that will make the function work properly.

Thanks for the awesome library!

**Comment by daaain** [comment]
Hey,

Ah, thanks a lot for the kind words :)

That's a nasty bug, thanks for the spot!

Would you mind submitting a pull request so that you get the credit for fixing this? :)

**Comment by bobvoorneveld** [comment]
np, but this is the first time I'm doing this for a repo i'm not participating in. Do you know how to do make one?

**Comment by daaain** [comment]
It's not that complicated, fork my repo under your user, clone it, do the change and commit it, push it back to your fork, open your fork on Github and press the `Compare and Review` button.

Github has a nice little guide which covers this in a little bit more details: https://help.github.com/articles/creating-a-pull-request

**Comment by bobvoorneveld** [comment]
done. should be there...

**Comment by daaain** [comment]
Perfect, thanks a lot :)
