### ISSUE TITLE
error undefined function

### ISSUE THREAD

**Issue by lama512** [daaain/JSSoundRecorder#5]
hello.i was running your demo few weeks ago and it was working well but last Friday i run the demo and an error starts to appear of undefined function.I updated the chrome but still same error please run your demo and check the console to see the problem.waiting your reply

**Comment by daaain** [comment]
Hey,

I just tried it and works for me, can you please paste the full error message and your browser / system info?

**Comment by lama512** [comment]
seems that the web audio api's need to be updated I did the following:
createGainNode()---->createNode()
createDelayNode()----->createDelay()
createJavascriptNode()----->createScriptProcessor()
once these updates are involved the program works right
thank you for your reply though.

**Comment by lama512** [comment]
how can I get in contact with you?

**Comment by daaain** [comment]
Really sorry for the late reply, I was away on long holiday and just getting through my email backlog.

Right, I read a bit about these methods and found a good writeup: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Porting_webkitAudioContext_code_to_standards_based_AudioContext

If you have time to put it together, a pull request would be super appreciated!
