### ISSUE TITLE
Only echo and can't hear my  voice

### ISSUE THREAD

**Issue by sdrraja** [daaain/JSSoundRecorder#7]
I can't hear my  voice back.What  should i do??

**Comment by daaain** [comment]
Hey,

Well, the first thing I'd say is to try it with headphones, there isn't any code in there to prevent feedback.

And also the usual advice of making sure all the system audio settings are fine, etc.

Also make sure that you're using an up to date, evergreen browser (Firefox, Chrome, etc).

Sorry if that's not very helpful, but difficult to know what's the issue as it's most likely a hardware / system related one.
