### ISSUE TITLE
help me?

### ISSUE THREAD

**Issue by majiajue** [daaain/JSSoundRecorder#8]
Can I ask how to set the bit rate of 128 kbps rather than 1536 kbps

**Comment by daaain** [comment]
Hey @majiajue, I don't think you can set bitrate directly on WAV files, but you can change the sample rate or interleave to mono, etc, have a look at this discussion for example: http://stackoverflow.com/questions/16296645/decrease-bitrate-on-wav-file-created-with-recorderjs

You can also plug in an MP3 encoding library: http://audior.ec/blog/recording-mp3-using-only-html5-and-javascript-recordmp3-js/
